# Generated by Django 4.0.3 on 2022-06-21 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('phone_number', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('employee_number', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sold',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('sold', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='automobilevo',
            name='vin',
            field=models.CharField(default=12345678910, max_length=17, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SalesForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sales_rest.customer')),
                ('sales_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sales_rest.salesperson')),
                ('sold', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sales_rest.sold')),
                ('vin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sales_rest.automobilevo')),
            ],
        ),
    ]
