# Generated by Django 4.0.3 on 2022-06-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_customer_salesperson_sold_automobilevo_vin_salesform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilevo',
            name='import_href',
            field=models.CharField(max_length=400, unique=True),
        ),
    ]
