# Generated by Django 4.0.3 on 2022-06-21 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0004_remove_automobilevo_import_href'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesform',
            name='sold',
        ),
        migrations.AddField(
            model_name='sold',
            name='sales_form',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sold', to='sales_rest.salesform'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sold',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sold',
            name='sold',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
