# Generated by Django 4.0.3 on 2022-06-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='employee_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
