# Generated by Django 4.0.3 on 2022-06-21 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0007_remove_automobilevo_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='car_vin',
            field=models.CharField(max_length=17, null=True, unique=True),
        ),
    ]
